// Generated by anchor_to_vas.py from raw Anchor source.
// This is a type-stripped VAS model, not a full Anchor runtime model.
pub type Pubkey = u32;

// @account
pub struct Account {
    pub authority: Pubkey,
    pub total_supply: u64,
}

// @account
pub struct Batch {
    pub multisig: Pubkey,
    pub creator: Pubkey,
    pub index: u64,
    pub vault_index: u8,
    pub vault_bump: u8,
    pub size: u32,
    pub executed_transaction_index: u32,
}

// @account
pub struct BatchAccountsClose {
    pub multisig: Account,
    pub proposal: Pubkey,
    pub batch: Account,
    pub rent_collector: Pubkey,
    pub system_program: Pubkey,
}

// @account
pub struct BatchAddTransaction {
    pub multisig: Account,
    pub proposal: Account,
    pub batch: Account,
    pub transaction: Account,
    pub member: Pubkey,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
}

// @account
pub struct BatchAddTransactionArgs {
    pub ephemeral_signers: u8,
    pub transaction_message: u64,
}

// @account
pub struct BatchCreate {
    pub multisig: Account,
    pub batch: Account,
    pub creator: Pubkey,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
}

// @account
pub struct BatchCreateArgs {
    pub vault_index: u8,
    pub memo: u64,
}

// @account
pub struct BatchExecuteTransaction {
    pub multisig: Account,
    pub member: Pubkey,
    pub proposal: Account,
    pub batch: Account,
    pub transaction: Account,
}

// @account
pub struct CompiledInstruction {
    pub program_id_index: u8,
    pub account_indexes: SmallVec,
    pub data: SmallVec,
}

// @account
pub struct ConfigTransaction {
    pub multisig: Pubkey,
    pub creator: Pubkey,
    pub index: u64,
    pub actions: u64,
}

// @account
pub struct ConfigTransactionAccountsClose {
    pub multisig: Account,
    pub proposal: Pubkey,
    pub transaction: Account,
    pub rent_collector: Pubkey,
    pub system_program: Pubkey,
}

// @account
pub struct ConfigTransactionCreate {
    pub multisig: Account,
    pub transaction: Account,
    pub creator: Pubkey,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
}

// @account
pub struct ConfigTransactionCreateArgs {
    pub actions: u64,
    pub memo: u64,
}

// @account
pub struct ConfigTransactionExecute {
    pub multisig: Account,
    pub member: Pubkey,
    pub proposal: Account,
    pub transaction: Account,
    pub rent_payer: u64,
    pub system_program: u64,
}

// @account
pub struct Deprecated {
    pub null: Pubkey,
}

// @account
pub struct ExecutableTransactionMessage {
    pub message: VaultTransactionMessage,
    pub static_accounts: u64,
    pub loaded_writable_accounts: u64,
    pub loaded_readonly_accounts: u64,
}

// @account
pub struct Member {
    pub key: Pubkey,
    pub permissions: Permissions,
}

// @account
pub struct MessageAddressTableLookup {
    pub account_key: Pubkey,
    pub writable_indexes: SmallVec,
    pub readonly_indexes: SmallVec,
}

// @account
pub struct Multisig {
    pub create_key: Pubkey,
    pub config_authority: Pubkey,
    pub threshold: u16,
    pub time_lock: u32,
    pub transaction_index: u64,
    pub stale_transaction_index: u64,
    pub rent_collector: u64,
    pub members: u64,
}

// @account
pub struct MultisigAddMemberArgs {
    pub new_member: Member,
    pub memo: u64,
}

// @account
pub struct MultisigAddSpendingLimit {
    pub multisig: Account,
    pub config_authority: Pubkey,
    pub spending_limit: Account,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
}

// @account
pub struct MultisigAddSpendingLimitArgs {
    pub create_key: Pubkey,
    pub vault_index: u8,
    pub mint: Pubkey,
    pub amount: u64,
    pub period: Period,
    pub members: u64,
    pub destinations: u64,
    pub memo: u64,
}

// @account
pub struct MultisigChangeThresholdArgs {
    pub new_threshold: u16,
    pub memo: u64,
}

// @account
pub struct MultisigCompiledInstruction {
    pub program_id_index: u8,
    pub account_indexes: u64,
    pub data: u64,
}

// @account
pub struct MultisigConfig {
    pub multisig: Account,
    pub config_authority: Pubkey,
    pub rent_payer: u64,
    pub system_program: u64,
}

// @account
pub struct MultisigCreateV2 {
    pub program_config: Account,
    pub treasury: Pubkey,
    pub multisig: Account,
    pub create_key: Pubkey,
    pub creator: Pubkey,
    pub system_program: Pubkey,
}

// @account
pub struct MultisigMessageAddressTableLookup {
    pub account_key: Pubkey,
    pub writable_indexes: u64,
    pub readonly_indexes: u64,
}

// @account
pub struct MultisigRemoveMemberArgs {
    pub old_member: Pubkey,
    pub memo: u64,
}

// @account
pub struct MultisigRemoveSpendingLimit {
    pub multisig: Account,
    pub config_authority: Pubkey,
    pub spending_limit: Account,
    pub rent_collector: Pubkey,
}

// @account
pub struct MultisigRemoveSpendingLimitArgs {
    pub memo: u64,
}

// @account
pub struct MultisigSetConfigAuthorityArgs {
    pub config_authority: Pubkey,
    pub memo: u64,
}

// @account
pub struct MultisigSetRentCollectorArgs {
    pub rent_collector: u64,
    pub memo: u64,
}

// @account
pub struct MultisigSetTimeLockArgs {
    pub time_lock: u32,
    pub memo: u64,
}

// @account
pub struct Period {
    pub authority: Pubkey,
    pub total_supply: u64,
}

// @account
pub struct Permissions {
    pub mask: u8,
}

// @account
pub struct ProgramConfig {
    pub authority: Pubkey,
    pub multisig_creation_fee: u64,
    pub treasury: Pubkey,
    pub _reserved: u64,
}

// @account
pub struct ProgramConfigInit {
    pub program_config: Account,
    pub initializer: Pubkey,
    pub system_program: Pubkey,
}

// @account
pub struct ProgramConfigInitArgs {
    pub authority: Pubkey,
    pub multisig_creation_fee: u64,
    pub treasury: Pubkey,
}

// @account
pub struct ProgramConfigSetAuthorityArgs {
    pub new_authority: Pubkey,
}

// @account
pub struct ProgramConfigSetMultisigCreationFeeArgs {
    pub new_multisig_creation_fee: u64,
}

// @account
pub struct ProgramConfigSetTreasuryArgs {
    pub new_treasury: Pubkey,
}

// @account
pub struct Proposal {
    pub multisig: Pubkey,
    pub transaction_index: u64,
    pub status: ProposalStatus,
    pub approved: u64,
    pub rejected: u64,
    pub cancelled: u64,
}

// @account
pub struct ProposalActivate {
    pub multisig: Account,
    pub member: Pubkey,
    pub proposal: Account,
}

// @account
pub struct ProposalCancelV2 {
    pub proposal_vote: ProposalVote,
    pub system_program: Pubkey,
}

// @account
pub struct ProposalCreate {
    pub multisig: Account,
    pub proposal: Account,
    pub creator: Pubkey,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
}

// @account
pub struct ProposalCreateArgs {
    pub transaction_index: u64,
    pub draft: bool,
}

// @account
pub struct ProposalStatus {
    pub authority: Pubkey,
    pub total_supply: u64,
}

// @account
pub struct ProposalVote {
    pub multisig: Account,
    pub member: Pubkey,
    pub proposal: Account,
}

// @account
pub struct ProposalVoteArgs {
    pub memo: u64,
}

// @account
pub struct SmallVec {
    pub authority: Pubkey,
    pub total_supply: u64,
}

// @account
pub struct SpendingLimit {
    pub multisig: Pubkey,
    pub create_key: Pubkey,
    pub vault_index: u8,
    pub mint: Pubkey,
    pub amount: u64,
    pub period: Period,
    pub remaining_amount: u64,
    pub last_reset: i64,
    pub members: u64,
    pub destinations: u64,
}

// @account
pub struct SpendingLimitUse {
    pub multisig: Account,
    pub member: Pubkey,
    pub spending_limit: Account,
    pub vault: Pubkey,
    pub destination: Pubkey,
    pub system_program: u64,
    pub mint: u64,
    pub vault_token_account: u64,
    pub destination_token_account: u64,
    pub token_program: u64,
}

// @account
pub struct SpendingLimitUseArgs {
    pub amount: u64,
    pub decimals: u8,
    pub memo: u64,
}

// @account
pub struct TransactionBuffer {
    pub multisig: Pubkey,
    pub creator: Pubkey,
    pub buffer_index: u8,
    pub vault_index: u8,
    pub final_buffer_hash: u64,
    pub final_buffer_size: u16,
    pub buffer: u64,
}

// @account
pub struct TransactionBufferClose {
    pub multisig: Account,
    pub transaction_buffer: Account,
    pub creator: Pubkey,
}

// @account
pub struct TransactionBufferCreate {
    pub multisig: Account,
    pub transaction_buffer: Account,
    pub creator: Pubkey,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
}

// @account
pub struct TransactionBufferCreateArgs {
    pub buffer_index: u8,
    pub vault_index: u8,
    pub final_buffer_hash: u64,
    pub final_buffer_size: u16,
    pub buffer: u64,
}

// @account
pub struct TransactionBufferExtend {
    pub multisig: Account,
    pub transaction_buffer: Account,
    pub creator: Pubkey,
}

// @account
pub struct TransactionBufferExtendArgs {
    pub buffer: u64,
}

// @account
pub struct TransactionMessage {
    pub num_signers: u8,
    pub num_writable_signers: u8,
    pub num_writable_non_signers: u8,
    pub account_keys: SmallVec,
    pub instructions: SmallVec,
    pub address_table_lookups: SmallVec,
}

// @account
pub struct VaultBatchTransaction {
    pub ephemeral_signer_bumps: u64,
    pub message: VaultTransactionMessage,
}

// @account
pub struct VaultBatchTransactionAccountClose {
    pub multisig: Account,
    pub proposal: Account,
    pub batch: Account,
    pub transaction: Account,
    pub rent_collector: Pubkey,
    pub system_program: Pubkey,
}

// @account
pub struct VaultTransaction {
    pub multisig: Pubkey,
    pub creator: Pubkey,
    pub index: u64,
    pub vault_index: u8,
    pub vault_bump: u8,
    pub ephemeral_signer_bumps: u64,
    pub message: VaultTransactionMessage,
}

// @account
pub struct VaultTransactionAccountsClose {
    pub multisig: Account,
    pub proposal: Pubkey,
    pub transaction: Account,
    pub rent_collector: Pubkey,
    pub system_program: Pubkey,
}

// @account
pub struct VaultTransactionCreate {
    pub multisig: Account,
    pub transaction: Account,
    pub creator: Pubkey,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
}

// @account
pub struct VaultTransactionCreateArgs {
    pub vault_index: u8,
    pub ephemeral_signers: u8,
    pub transaction_message: u64,
    pub memo: u64,
}

// @account
pub struct VaultTransactionCreateFromBuffer {
    pub vault_transaction_create: VaultTransactionCreate,
    pub transaction_buffer: Account,
    pub creator: Pubkey,
}

// @account
pub struct VaultTransactionExecute {
    pub multisig: Account,
    pub proposal: Account,
    pub transaction: Account,
    pub member: Pubkey,
}

// @account
pub struct VaultTransactionMessage {
    pub num_signers: u8,
    pub num_writable_signers: u8,
    pub num_writable_non_signers: u8,
    pub account_keys: u64,
    pub instructions: u64,
    pub address_table_lookups: u64,
}

// @context
pub struct BatchAccountsCloseCtx {
    pub multisig: Account,
    pub proposal: Pubkey,
    pub batch: Account,
    pub rent_collector: Pubkey,
    pub system_program: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct BatchAddTransactionCtx {
    pub multisig: Account,
    pub proposal: Account,
    pub batch: Account,
    pub transaction: Account,
    pub member: Pubkey,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct BatchCreateCtx {
    pub multisig: Account,
    pub batch: Account,
    pub creator: Pubkey,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct BatchExecuteTransactionCtx {
    pub multisig: Account,
    pub member: Pubkey,
    pub proposal: Account,
    pub batch: Account,
    pub transaction: Account,
    pub is_signer: bool,
}

// @context
pub struct ConfigTransactionAccountsCloseCtx {
    pub multisig: Account,
    pub proposal: Pubkey,
    pub transaction: Account,
    pub rent_collector: Pubkey,
    pub system_program: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct ConfigTransactionCreateCtx {
    pub multisig: Account,
    pub transaction: Account,
    pub creator: Pubkey,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct ConfigTransactionExecuteCtx {
    pub multisig: Account,
    pub member: Pubkey,
    pub proposal: Account,
    pub transaction: Account,
    pub rent_payer: u64,
    pub system_program: u64,
    pub is_signer: bool,
}

// @context
pub struct DeprecatedCtx {
    pub null: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct MultisigAddSpendingLimitCtx {
    pub multisig: Account,
    pub config_authority: Pubkey,
    pub spending_limit: Account,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct MultisigConfigCtx {
    pub multisig: Account,
    pub config_authority: Pubkey,
    pub rent_payer: u64,
    pub system_program: u64,
    pub is_signer: bool,
}

// @context
pub struct MultisigCreateV2Ctx {
    pub program_config: Account,
    pub treasury: Pubkey,
    pub multisig: Account,
    pub create_key: Pubkey,
    pub creator: Pubkey,
    pub system_program: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct MultisigRemoveSpendingLimitCtx {
    pub multisig: Account,
    pub config_authority: Pubkey,
    pub spending_limit: Account,
    pub rent_collector: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct ProgramConfigCtx {
    pub program_config: ProgramConfig,
    pub authority: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct ProgramConfigInitCtx {
    pub program_config: Account,
    pub initializer: Pubkey,
    pub system_program: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct ProposalActivateCtx {
    pub multisig: Account,
    pub member: Pubkey,
    pub proposal: Account,
    pub is_signer: bool,
}

// @context
pub struct ProposalCancelV2Ctx {
    pub proposal_vote: ProposalVote,
    pub system_program: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct ProposalCreateCtx {
    pub multisig: Account,
    pub proposal: Account,
    pub creator: Pubkey,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct ProposalVoteCtx {
    pub multisig: Account,
    pub member: Pubkey,
    pub proposal: Account,
    pub is_signer: bool,
}

// @context
pub struct SpendingLimitUseCtx {
    pub multisig: Account,
    pub member: Pubkey,
    pub spending_limit: Account,
    pub vault: Pubkey,
    pub destination: Pubkey,
    pub system_program: u64,
    pub mint: u64,
    pub vault_token_account: u64,
    pub destination_token_account: u64,
    pub token_program: u64,
    pub is_signer: bool,
}

// @context
pub struct TransactionBufferCloseCtx {
    pub multisig: Account,
    pub transaction_buffer: Account,
    pub creator: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct TransactionBufferCreateCtx {
    pub multisig: Account,
    pub transaction_buffer: Account,
    pub creator: Pubkey,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct TransactionBufferExtendCtx {
    pub multisig: Account,
    pub transaction_buffer: Account,
    pub creator: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct VaultBatchTransactionAccountCloseCtx {
    pub multisig: Account,
    pub proposal: Account,
    pub batch: Account,
    pub transaction: Account,
    pub rent_collector: Pubkey,
    pub system_program: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct VaultTransactionAccountsCloseCtx {
    pub multisig: Account,
    pub proposal: Pubkey,
    pub transaction: Account,
    pub rent_collector: Pubkey,
    pub system_program: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct VaultTransactionCreateCtx {
    pub multisig: Account,
    pub transaction: Account,
    pub creator: Pubkey,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct VaultTransactionCreateFromBufferCtx {
    pub vault_transaction_create: VaultTransactionCreate,
    pub transaction_buffer: Account,
    pub creator: Pubkey,
    pub is_signer: bool,
}

// @context
pub struct VaultTransactionExecuteCtx {
    pub multisig: Account,
    pub proposal: Account,
    pub transaction: Account,
    pub member: Pubkey,
    pub is_signer: bool,
}

pub fn batch_add_transaction(ctx: &mut BatchAddTransactionCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn batch_create(ctx: &mut BatchCreateCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn batch_execute_transaction(ctx: &mut BatchExecuteTransactionCtx) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    Ok(())
}

pub fn config_transaction_create(ctx: &mut ConfigTransactionCreateCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn multisig_add_spending_limit(ctx: &mut MultisigAddSpendingLimitCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn multisig_add_member(ctx: &mut MultisigConfigCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn multisig_remove_member(ctx: &mut MultisigConfigCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn multisig_change_threshold(ctx: &mut MultisigConfigCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn multisig_set_time_lock(ctx: &mut MultisigConfigCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn multisig_set_config_authority(ctx: &mut MultisigConfigCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn multisig_set_rent_collector(ctx: &mut MultisigConfigCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn multisig_create(ctx: &mut MultisigCreateV2Ctx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn multisig_remove_spending_limit(ctx: &mut MultisigRemoveSpendingLimitCtx, _args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = _args;
    Ok(())
}

pub fn program_config_set_authority(ctx: &mut ProgramConfigCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn program_config_set_multisig_creation_fee(ctx: &mut ProgramConfigCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn program_config_set_treasury(ctx: &mut ProgramConfigCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn program_config_init(ctx: &mut ProgramConfigInitCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn proposal_activate(ctx: &mut ProposalActivateCtx) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    Ok(())
}

pub fn proposal_create(ctx: &mut ProposalCreateCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn proposal_approve(ctx: &mut ProposalVoteCtx, _args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = _args;
    Ok(())
}

pub fn proposal_reject(ctx: &mut ProposalVoteCtx, _args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = _args;
    Ok(())
}

pub fn proposal_cancel(ctx: &mut ProposalVoteCtx, _args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = _args;
    Ok(())
}

pub fn spending_limit_use(ctx: &mut SpendingLimitUseCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn config_transaction_accounts_close(ctx: &mut ConfigTransactionAccountsCloseCtx) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    Ok(())
}

pub fn vault_transaction_accounts_close(ctx: &mut VaultTransactionAccountsCloseCtx) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    Ok(())
}

pub fn vault_batch_transaction_account_close(ctx: &mut VaultBatchTransactionAccountCloseCtx) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    Ok(())
}

pub fn batch_accounts_close(ctx: &mut BatchAccountsCloseCtx) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    Ok(())
}

pub fn transaction_buffer_close(ctx: &mut TransactionBufferCloseCtx) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    Ok(())
}

pub fn transaction_buffer_create(ctx: &mut TransactionBufferCreateCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn transaction_buffer_extend(ctx: &mut TransactionBufferExtendCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn vault_transaction_create(ctx: &mut VaultTransactionCreateCtx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}

pub fn vault_transaction_execute(ctx: &mut VaultTransactionExecuteCtx) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    Ok(())
}

pub fn multisig_create_v2(ctx: &mut MultisigCreateV2Ctx, args: u64) -> Result<(), &'static str> {
    if !ctx.is_signer {
        return Err("not signer");
    }
    let _ = args;
    Ok(())
}
// ============================================================
// GENERATED BY VeriRust harness_generator.py — DO NOT EDIT
// ============================================================
#[cfg(kani)]
mod verirust_harnesses {
    use super::*;

    impl kani::Arbitrary for Account {
        fn any() -> Self {
            Account {
                authority: kani::any(),
                total_supply: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for Batch {
        fn any() -> Self {
            Batch {
                multisig: kani::any(),
                creator: kani::any(),
                index: kani::any(),
                vault_index: kani::any(),
                vault_bump: kani::any(),
                size: kani::any(),
                executed_transaction_index: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for BatchAccountsClose {
        fn any() -> Self {
            BatchAccountsClose {
                multisig: kani::any(),
                proposal: kani::any(),
                batch: kani::any(),
                rent_collector: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for BatchAddTransaction {
        fn any() -> Self {
            BatchAddTransaction {
                multisig: kani::any(),
                proposal: kani::any(),
                batch: kani::any(),
                transaction: kani::any(),
                member: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for BatchAddTransactionArgs {
        fn any() -> Self {
            BatchAddTransactionArgs {
                ephemeral_signers: kani::any(),
                transaction_message: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for BatchCreate {
        fn any() -> Self {
            BatchCreate {
                multisig: kani::any(),
                batch: kani::any(),
                creator: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for BatchCreateArgs {
        fn any() -> Self {
            BatchCreateArgs {
                vault_index: kani::any(),
                memo: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for BatchExecuteTransaction {
        fn any() -> Self {
            BatchExecuteTransaction {
                multisig: kani::any(),
                member: kani::any(),
                proposal: kani::any(),
                batch: kani::any(),
                transaction: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for CompiledInstruction {
        fn any() -> Self {
            CompiledInstruction {
                program_id_index: kani::any(),
                account_indexes: kani::any(),
                data: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ConfigTransaction {
        fn any() -> Self {
            ConfigTransaction {
                multisig: kani::any(),
                creator: kani::any(),
                index: kani::any(),
                actions: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ConfigTransactionAccountsClose {
        fn any() -> Self {
            ConfigTransactionAccountsClose {
                multisig: kani::any(),
                proposal: kani::any(),
                transaction: kani::any(),
                rent_collector: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ConfigTransactionCreate {
        fn any() -> Self {
            ConfigTransactionCreate {
                multisig: kani::any(),
                transaction: kani::any(),
                creator: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ConfigTransactionCreateArgs {
        fn any() -> Self {
            ConfigTransactionCreateArgs {
                actions: kani::any(),
                memo: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ConfigTransactionExecute {
        fn any() -> Self {
            ConfigTransactionExecute {
                multisig: kani::any(),
                member: kani::any(),
                proposal: kani::any(),
                transaction: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for Deprecated {
        fn any() -> Self {
            Deprecated {
                null: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ExecutableTransactionMessage {
        fn any() -> Self {
            ExecutableTransactionMessage {
                message: kani::any(),
                static_accounts: kani::any(),
                loaded_writable_accounts: kani::any(),
                loaded_readonly_accounts: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for Member {
        fn any() -> Self {
            Member {
                key: kani::any(),
                permissions: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MessageAddressTableLookup {
        fn any() -> Self {
            MessageAddressTableLookup {
                account_key: kani::any(),
                writable_indexes: kani::any(),
                readonly_indexes: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for Multisig {
        fn any() -> Self {
            Multisig {
                create_key: kani::any(),
                config_authority: kani::any(),
                threshold: kani::any(),
                time_lock: kani::any(),
                transaction_index: kani::any(),
                stale_transaction_index: kani::any(),
                rent_collector: kani::any(),
                members: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigAddMemberArgs {
        fn any() -> Self {
            MultisigAddMemberArgs {
                new_member: kani::any(),
                memo: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigAddSpendingLimit {
        fn any() -> Self {
            MultisigAddSpendingLimit {
                multisig: kani::any(),
                config_authority: kani::any(),
                spending_limit: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigAddSpendingLimitArgs {
        fn any() -> Self {
            MultisigAddSpendingLimitArgs {
                create_key: kani::any(),
                vault_index: kani::any(),
                mint: kani::any(),
                amount: kani::any(),
                period: kani::any(),
                members: kani::any(),
                destinations: kani::any(),
                memo: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigChangeThresholdArgs {
        fn any() -> Self {
            MultisigChangeThresholdArgs {
                new_threshold: kani::any(),
                memo: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigCompiledInstruction {
        fn any() -> Self {
            MultisigCompiledInstruction {
                program_id_index: kani::any(),
                account_indexes: kani::any(),
                data: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigConfig {
        fn any() -> Self {
            MultisigConfig {
                multisig: kani::any(),
                config_authority: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigCreateV2 {
        fn any() -> Self {
            MultisigCreateV2 {
                program_config: kani::any(),
                treasury: kani::any(),
                multisig: kani::any(),
                create_key: kani::any(),
                creator: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigMessageAddressTableLookup {
        fn any() -> Self {
            MultisigMessageAddressTableLookup {
                account_key: kani::any(),
                writable_indexes: kani::any(),
                readonly_indexes: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigRemoveMemberArgs {
        fn any() -> Self {
            MultisigRemoveMemberArgs {
                old_member: kani::any(),
                memo: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigRemoveSpendingLimit {
        fn any() -> Self {
            MultisigRemoveSpendingLimit {
                multisig: kani::any(),
                config_authority: kani::any(),
                spending_limit: kani::any(),
                rent_collector: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigRemoveSpendingLimitArgs {
        fn any() -> Self {
            MultisigRemoveSpendingLimitArgs {
                memo: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigSetConfigAuthorityArgs {
        fn any() -> Self {
            MultisigSetConfigAuthorityArgs {
                config_authority: kani::any(),
                memo: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigSetRentCollectorArgs {
        fn any() -> Self {
            MultisigSetRentCollectorArgs {
                rent_collector: kani::any(),
                memo: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigSetTimeLockArgs {
        fn any() -> Self {
            MultisigSetTimeLockArgs {
                time_lock: kani::any(),
                memo: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for Period {
        fn any() -> Self {
            Period {
                authority: kani::any(),
                total_supply: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for Permissions {
        fn any() -> Self {
            Permissions {
                mask: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProgramConfig {
        fn any() -> Self {
            ProgramConfig {
                authority: kani::any(),
                multisig_creation_fee: kani::any(),
                treasury: kani::any(),
                _reserved: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProgramConfigInit {
        fn any() -> Self {
            ProgramConfigInit {
                program_config: kani::any(),
                initializer: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProgramConfigInitArgs {
        fn any() -> Self {
            ProgramConfigInitArgs {
                authority: kani::any(),
                multisig_creation_fee: kani::any(),
                treasury: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProgramConfigSetAuthorityArgs {
        fn any() -> Self {
            ProgramConfigSetAuthorityArgs {
                new_authority: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProgramConfigSetMultisigCreationFeeArgs {
        fn any() -> Self {
            ProgramConfigSetMultisigCreationFeeArgs {
                new_multisig_creation_fee: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProgramConfigSetTreasuryArgs {
        fn any() -> Self {
            ProgramConfigSetTreasuryArgs {
                new_treasury: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for Proposal {
        fn any() -> Self {
            Proposal {
                multisig: kani::any(),
                transaction_index: kani::any(),
                status: kani::any(),
                approved: kani::any(),
                rejected: kani::any(),
                cancelled: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProposalActivate {
        fn any() -> Self {
            ProposalActivate {
                multisig: kani::any(),
                member: kani::any(),
                proposal: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProposalCancelV2 {
        fn any() -> Self {
            ProposalCancelV2 {
                proposal_vote: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProposalCreate {
        fn any() -> Self {
            ProposalCreate {
                multisig: kani::any(),
                proposal: kani::any(),
                creator: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProposalCreateArgs {
        fn any() -> Self {
            ProposalCreateArgs {
                transaction_index: kani::any(),
                draft: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProposalStatus {
        fn any() -> Self {
            ProposalStatus {
                authority: kani::any(),
                total_supply: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProposalVote {
        fn any() -> Self {
            ProposalVote {
                multisig: kani::any(),
                member: kani::any(),
                proposal: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProposalVoteArgs {
        fn any() -> Self {
            ProposalVoteArgs {
                memo: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for SmallVec {
        fn any() -> Self {
            SmallVec {
                authority: kani::any(),
                total_supply: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for SpendingLimit {
        fn any() -> Self {
            SpendingLimit {
                multisig: kani::any(),
                create_key: kani::any(),
                vault_index: kani::any(),
                mint: kani::any(),
                amount: kani::any(),
                period: kani::any(),
                remaining_amount: kani::any(),
                last_reset: kani::any(),
                members: kani::any(),
                destinations: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for SpendingLimitUse {
        fn any() -> Self {
            SpendingLimitUse {
                multisig: kani::any(),
                member: kani::any(),
                spending_limit: kani::any(),
                vault: kani::any(),
                destination: kani::any(),
                system_program: kani::any(),
                mint: kani::any(),
                vault_token_account: kani::any(),
                destination_token_account: kani::any(),
                token_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for SpendingLimitUseArgs {
        fn any() -> Self {
            SpendingLimitUseArgs {
                amount: kani::any(),
                decimals: kani::any(),
                memo: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for TransactionBuffer {
        fn any() -> Self {
            TransactionBuffer {
                multisig: kani::any(),
                creator: kani::any(),
                buffer_index: kani::any(),
                vault_index: kani::any(),
                final_buffer_hash: kani::any(),
                final_buffer_size: kani::any(),
                buffer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for TransactionBufferClose {
        fn any() -> Self {
            TransactionBufferClose {
                multisig: kani::any(),
                transaction_buffer: kani::any(),
                creator: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for TransactionBufferCreate {
        fn any() -> Self {
            TransactionBufferCreate {
                multisig: kani::any(),
                transaction_buffer: kani::any(),
                creator: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for TransactionBufferCreateArgs {
        fn any() -> Self {
            TransactionBufferCreateArgs {
                buffer_index: kani::any(),
                vault_index: kani::any(),
                final_buffer_hash: kani::any(),
                final_buffer_size: kani::any(),
                buffer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for TransactionBufferExtend {
        fn any() -> Self {
            TransactionBufferExtend {
                multisig: kani::any(),
                transaction_buffer: kani::any(),
                creator: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for TransactionBufferExtendArgs {
        fn any() -> Self {
            TransactionBufferExtendArgs {
                buffer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for TransactionMessage {
        fn any() -> Self {
            TransactionMessage {
                num_signers: kani::any(),
                num_writable_signers: kani::any(),
                num_writable_non_signers: kani::any(),
                account_keys: kani::any(),
                instructions: kani::any(),
                address_table_lookups: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for VaultBatchTransaction {
        fn any() -> Self {
            VaultBatchTransaction {
                ephemeral_signer_bumps: kani::any(),
                message: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for VaultBatchTransactionAccountClose {
        fn any() -> Self {
            VaultBatchTransactionAccountClose {
                multisig: kani::any(),
                proposal: kani::any(),
                batch: kani::any(),
                transaction: kani::any(),
                rent_collector: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for VaultTransaction {
        fn any() -> Self {
            VaultTransaction {
                multisig: kani::any(),
                creator: kani::any(),
                index: kani::any(),
                vault_index: kani::any(),
                vault_bump: kani::any(),
                ephemeral_signer_bumps: kani::any(),
                message: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for VaultTransactionAccountsClose {
        fn any() -> Self {
            VaultTransactionAccountsClose {
                multisig: kani::any(),
                proposal: kani::any(),
                transaction: kani::any(),
                rent_collector: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for VaultTransactionCreate {
        fn any() -> Self {
            VaultTransactionCreate {
                multisig: kani::any(),
                transaction: kani::any(),
                creator: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for VaultTransactionCreateArgs {
        fn any() -> Self {
            VaultTransactionCreateArgs {
                vault_index: kani::any(),
                ephemeral_signers: kani::any(),
                transaction_message: kani::any(),
                memo: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for VaultTransactionCreateFromBuffer {
        fn any() -> Self {
            VaultTransactionCreateFromBuffer {
                vault_transaction_create: kani::any(),
                transaction_buffer: kani::any(),
                creator: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for VaultTransactionExecute {
        fn any() -> Self {
            VaultTransactionExecute {
                multisig: kani::any(),
                proposal: kani::any(),
                transaction: kani::any(),
                member: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for VaultTransactionMessage {
        fn any() -> Self {
            VaultTransactionMessage {
                num_signers: kani::any(),
                num_writable_signers: kani::any(),
                num_writable_non_signers: kani::any(),
                account_keys: kani::any(),
                instructions: kani::any(),
                address_table_lookups: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for BatchAccountsCloseCtx {
        fn any() -> Self {
            BatchAccountsCloseCtx {
                multisig: kani::any(),
                proposal: kani::any(),
                batch: kani::any(),
                rent_collector: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for BatchAddTransactionCtx {
        fn any() -> Self {
            BatchAddTransactionCtx {
                multisig: kani::any(),
                proposal: kani::any(),
                batch: kani::any(),
                transaction: kani::any(),
                member: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for BatchCreateCtx {
        fn any() -> Self {
            BatchCreateCtx {
                multisig: kani::any(),
                batch: kani::any(),
                creator: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for BatchExecuteTransactionCtx {
        fn any() -> Self {
            BatchExecuteTransactionCtx {
                multisig: kani::any(),
                member: kani::any(),
                proposal: kani::any(),
                batch: kani::any(),
                transaction: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ConfigTransactionAccountsCloseCtx {
        fn any() -> Self {
            ConfigTransactionAccountsCloseCtx {
                multisig: kani::any(),
                proposal: kani::any(),
                transaction: kani::any(),
                rent_collector: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ConfigTransactionCreateCtx {
        fn any() -> Self {
            ConfigTransactionCreateCtx {
                multisig: kani::any(),
                transaction: kani::any(),
                creator: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ConfigTransactionExecuteCtx {
        fn any() -> Self {
            ConfigTransactionExecuteCtx {
                multisig: kani::any(),
                member: kani::any(),
                proposal: kani::any(),
                transaction: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for DeprecatedCtx {
        fn any() -> Self {
            DeprecatedCtx {
                null: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigAddSpendingLimitCtx {
        fn any() -> Self {
            MultisigAddSpendingLimitCtx {
                multisig: kani::any(),
                config_authority: kani::any(),
                spending_limit: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigConfigCtx {
        fn any() -> Self {
            MultisigConfigCtx {
                multisig: kani::any(),
                config_authority: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigCreateV2Ctx {
        fn any() -> Self {
            MultisigCreateV2Ctx {
                program_config: kani::any(),
                treasury: kani::any(),
                multisig: kani::any(),
                create_key: kani::any(),
                creator: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for MultisigRemoveSpendingLimitCtx {
        fn any() -> Self {
            MultisigRemoveSpendingLimitCtx {
                multisig: kani::any(),
                config_authority: kani::any(),
                spending_limit: kani::any(),
                rent_collector: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProgramConfigCtx {
        fn any() -> Self {
            ProgramConfigCtx {
                program_config: kani::any(),
                authority: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProgramConfigInitCtx {
        fn any() -> Self {
            ProgramConfigInitCtx {
                program_config: kani::any(),
                initializer: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProposalActivateCtx {
        fn any() -> Self {
            ProposalActivateCtx {
                multisig: kani::any(),
                member: kani::any(),
                proposal: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProposalCancelV2Ctx {
        fn any() -> Self {
            ProposalCancelV2Ctx {
                proposal_vote: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProposalCreateCtx {
        fn any() -> Self {
            ProposalCreateCtx {
                multisig: kani::any(),
                proposal: kani::any(),
                creator: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for ProposalVoteCtx {
        fn any() -> Self {
            ProposalVoteCtx {
                multisig: kani::any(),
                member: kani::any(),
                proposal: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for SpendingLimitUseCtx {
        fn any() -> Self {
            SpendingLimitUseCtx {
                multisig: kani::any(),
                member: kani::any(),
                spending_limit: kani::any(),
                vault: kani::any(),
                destination: kani::any(),
                system_program: kani::any(),
                mint: kani::any(),
                vault_token_account: kani::any(),
                destination_token_account: kani::any(),
                token_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for TransactionBufferCloseCtx {
        fn any() -> Self {
            TransactionBufferCloseCtx {
                multisig: kani::any(),
                transaction_buffer: kani::any(),
                creator: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for TransactionBufferCreateCtx {
        fn any() -> Self {
            TransactionBufferCreateCtx {
                multisig: kani::any(),
                transaction_buffer: kani::any(),
                creator: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for TransactionBufferExtendCtx {
        fn any() -> Self {
            TransactionBufferExtendCtx {
                multisig: kani::any(),
                transaction_buffer: kani::any(),
                creator: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for VaultBatchTransactionAccountCloseCtx {
        fn any() -> Self {
            VaultBatchTransactionAccountCloseCtx {
                multisig: kani::any(),
                proposal: kani::any(),
                batch: kani::any(),
                transaction: kani::any(),
                rent_collector: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for VaultTransactionAccountsCloseCtx {
        fn any() -> Self {
            VaultTransactionAccountsCloseCtx {
                multisig: kani::any(),
                proposal: kani::any(),
                transaction: kani::any(),
                rent_collector: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for VaultTransactionCreateCtx {
        fn any() -> Self {
            VaultTransactionCreateCtx {
                multisig: kani::any(),
                transaction: kani::any(),
                creator: kani::any(),
                rent_payer: kani::any(),
                system_program: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for VaultTransactionCreateFromBufferCtx {
        fn any() -> Self {
            VaultTransactionCreateFromBufferCtx {
                vault_transaction_create: kani::any(),
                transaction_buffer: kani::any(),
                creator: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    impl kani::Arbitrary for VaultTransactionExecuteCtx {
        fn any() -> Self {
            VaultTransactionExecuteCtx {
                multisig: kani::any(),
                proposal: kani::any(),
                transaction: kani::any(),
                member: kani::any(),
                is_signer: kani::any(),
            }
        }
    }

    // Safety harness: batch_add_transaction — detect arithmetic panics
    #[kani::proof]
    fn verify_batch_add_transaction() {
        let mut ctx: BatchAddTransactionCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = batch_add_transaction(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: batch_create — detect arithmetic panics
    #[kani::proof]
    fn verify_batch_create() {
        let mut ctx: BatchCreateCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = batch_create(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: batch_execute_transaction — detect arithmetic panics
    #[kani::proof]
    fn verify_batch_execute_transaction() {
        let mut ctx: BatchExecuteTransactionCtx = kani::any();
        kani::assume(ctx.is_signer);
        let _ = batch_execute_transaction(&mut ctx);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: config_transaction_create — detect arithmetic panics
    #[kani::proof]
    fn verify_config_transaction_create() {
        let mut ctx: ConfigTransactionCreateCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = config_transaction_create(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: multisig_add_spending_limit — detect arithmetic panics
    #[kani::proof]
    fn verify_multisig_add_spending_limit() {
        let mut ctx: MultisigAddSpendingLimitCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = multisig_add_spending_limit(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: multisig_add_member — detect arithmetic panics
    #[kani::proof]
    fn verify_multisig_add_member() {
        let mut ctx: MultisigConfigCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = multisig_add_member(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: multisig_remove_member — detect arithmetic panics
    #[kani::proof]
    fn verify_multisig_remove_member() {
        let mut ctx: MultisigConfigCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = multisig_remove_member(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: multisig_change_threshold — detect arithmetic panics
    #[kani::proof]
    fn verify_multisig_change_threshold() {
        let mut ctx: MultisigConfigCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = multisig_change_threshold(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: multisig_set_time_lock — detect arithmetic panics
    #[kani::proof]
    fn verify_multisig_set_time_lock() {
        let mut ctx: MultisigConfigCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = multisig_set_time_lock(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: multisig_set_config_authority — detect arithmetic panics
    #[kani::proof]
    fn verify_multisig_set_config_authority() {
        let mut ctx: MultisigConfigCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = multisig_set_config_authority(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: multisig_set_rent_collector — detect arithmetic panics
    #[kani::proof]
    fn verify_multisig_set_rent_collector() {
        let mut ctx: MultisigConfigCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = multisig_set_rent_collector(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: multisig_create — detect arithmetic panics
    #[kani::proof]
    fn verify_multisig_create() {
        let mut ctx: MultisigCreateV2Ctx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = multisig_create(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: multisig_remove_spending_limit — detect arithmetic panics
    #[kani::proof]
    fn verify_multisig_remove_spending_limit() {
        let mut ctx: MultisigRemoveSpendingLimitCtx = kani::any();
        let _args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = multisig_remove_spending_limit(&mut ctx, _args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: program_config_set_authority — detect arithmetic panics
    #[kani::proof]
    fn verify_program_config_set_authority() {
        let mut ctx: ProgramConfigCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        kani::assume(ctx.authority == ctx.program_config.authority);
        let _ = program_config_set_authority(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Auth harness: program_config_set_authority — non-owner must always be rejected
    #[kani::proof]
    fn verify_program_config_set_authority_auth() {
        let args: u64 = kani::any();
        let mut ctx: ProgramConfigCtx = kani::any();
        kani::assume(ctx.is_signer);
        // Force the attack scenario: caller is NOT the rightful owner
        kani::assume(ctx.authority != ctx.program_config.authority);
        kani::assume(args <= u64::MAX / 2);
        let result = program_config_set_authority(&mut ctx, args);
        assert!(
            result.is_err(),
            "AUTH_VIOLATION: program_config_set_authority succeeded without matching authority"
        );
    }

    // Safety harness: program_config_set_multisig_creation_fee — detect arithmetic panics
    #[kani::proof]
    fn verify_program_config_set_multisig_creation_fee() {
        let mut ctx: ProgramConfigCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        kani::assume(ctx.authority == ctx.program_config.authority);
        let _ = program_config_set_multisig_creation_fee(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Auth harness: program_config_set_multisig_creation_fee — non-owner must always be rejected
    #[kani::proof]
    fn verify_program_config_set_multisig_creation_fee_auth() {
        let args: u64 = kani::any();
        let mut ctx: ProgramConfigCtx = kani::any();
        kani::assume(ctx.is_signer);
        // Force the attack scenario: caller is NOT the rightful owner
        kani::assume(ctx.authority != ctx.program_config.authority);
        kani::assume(args <= u64::MAX / 2);
        let result = program_config_set_multisig_creation_fee(&mut ctx, args);
        assert!(
            result.is_err(),
            "AUTH_VIOLATION: program_config_set_multisig_creation_fee succeeded without matching authority"
        );
    }

    // Safety harness: program_config_set_treasury — detect arithmetic panics
    #[kani::proof]
    fn verify_program_config_set_treasury() {
        let mut ctx: ProgramConfigCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        kani::assume(ctx.authority == ctx.program_config.authority);
        let _ = program_config_set_treasury(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Auth harness: program_config_set_treasury — non-owner must always be rejected
    #[kani::proof]
    fn verify_program_config_set_treasury_auth() {
        let args: u64 = kani::any();
        let mut ctx: ProgramConfigCtx = kani::any();
        kani::assume(ctx.is_signer);
        // Force the attack scenario: caller is NOT the rightful owner
        kani::assume(ctx.authority != ctx.program_config.authority);
        kani::assume(args <= u64::MAX / 2);
        let result = program_config_set_treasury(&mut ctx, args);
        assert!(
            result.is_err(),
            "AUTH_VIOLATION: program_config_set_treasury succeeded without matching authority"
        );
    }

    // Safety harness: program_config_init — detect arithmetic panics
    #[kani::proof]
    fn verify_program_config_init() {
        let mut ctx: ProgramConfigInitCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = program_config_init(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: proposal_activate — detect arithmetic panics
    #[kani::proof]
    fn verify_proposal_activate() {
        let mut ctx: ProposalActivateCtx = kani::any();
        kani::assume(ctx.is_signer);
        let _ = proposal_activate(&mut ctx);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: proposal_create — detect arithmetic panics
    #[kani::proof]
    fn verify_proposal_create() {
        let mut ctx: ProposalCreateCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = proposal_create(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: proposal_approve — detect arithmetic panics
    #[kani::proof]
    fn verify_proposal_approve() {
        let mut ctx: ProposalVoteCtx = kani::any();
        let _args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = proposal_approve(&mut ctx, _args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: proposal_reject — detect arithmetic panics
    #[kani::proof]
    fn verify_proposal_reject() {
        let mut ctx: ProposalVoteCtx = kani::any();
        let _args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = proposal_reject(&mut ctx, _args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: proposal_cancel — detect arithmetic panics
    #[kani::proof]
    fn verify_proposal_cancel() {
        let mut ctx: ProposalVoteCtx = kani::any();
        let _args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = proposal_cancel(&mut ctx, _args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: spending_limit_use — detect arithmetic panics
    #[kani::proof]
    fn verify_spending_limit_use() {
        let mut ctx: SpendingLimitUseCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = spending_limit_use(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: config_transaction_accounts_close — detect arithmetic panics
    #[kani::proof]
    fn verify_config_transaction_accounts_close() {
        let mut ctx: ConfigTransactionAccountsCloseCtx = kani::any();
        kani::assume(ctx.is_signer);
        let _ = config_transaction_accounts_close(&mut ctx);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: vault_transaction_accounts_close — detect arithmetic panics
    #[kani::proof]
    fn verify_vault_transaction_accounts_close() {
        let mut ctx: VaultTransactionAccountsCloseCtx = kani::any();
        kani::assume(ctx.is_signer);
        let _ = vault_transaction_accounts_close(&mut ctx);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: vault_batch_transaction_account_close — detect arithmetic panics
    #[kani::proof]
    fn verify_vault_batch_transaction_account_close() {
        let mut ctx: VaultBatchTransactionAccountCloseCtx = kani::any();
        kani::assume(ctx.is_signer);
        let _ = vault_batch_transaction_account_close(&mut ctx);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: batch_accounts_close — detect arithmetic panics
    #[kani::proof]
    fn verify_batch_accounts_close() {
        let mut ctx: BatchAccountsCloseCtx = kani::any();
        kani::assume(ctx.is_signer);
        let _ = batch_accounts_close(&mut ctx);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: transaction_buffer_close — detect arithmetic panics
    #[kani::proof]
    fn verify_transaction_buffer_close() {
        let mut ctx: TransactionBufferCloseCtx = kani::any();
        kani::assume(ctx.is_signer);
        let _ = transaction_buffer_close(&mut ctx);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: transaction_buffer_create — detect arithmetic panics
    #[kani::proof]
    fn verify_transaction_buffer_create() {
        let mut ctx: TransactionBufferCreateCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = transaction_buffer_create(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: transaction_buffer_extend — detect arithmetic panics
    #[kani::proof]
    fn verify_transaction_buffer_extend() {
        let mut ctx: TransactionBufferExtendCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = transaction_buffer_extend(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: vault_transaction_create — detect arithmetic panics
    #[kani::proof]
    fn verify_vault_transaction_create() {
        let mut ctx: VaultTransactionCreateCtx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = vault_transaction_create(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: vault_transaction_execute — detect arithmetic panics
    #[kani::proof]
    fn verify_vault_transaction_execute() {
        let mut ctx: VaultTransactionExecuteCtx = kani::any();
        kani::assume(ctx.is_signer);
        let _ = vault_transaction_execute(&mut ctx);
        // Kani checks: no arithmetic panic, no assertion failure
    }

    // Safety harness: multisig_create_v2 — detect arithmetic panics
    #[kani::proof]
    fn verify_multisig_create_v2() {
        let mut ctx: MultisigCreateV2Ctx = kani::any();
        let args: u64 = kani::any();
        kani::assume(ctx.is_signer);
        let _ = multisig_create_v2(&mut ctx, args);
        // Kani checks: no arithmetic panic, no assertion failure
    }

}
